# This environment is intended to be used for running all notebooks of this repository.

name: environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - geopandas
  - shapely
  - pyproj
  - contextily
  - scikit-learn
  - joblib
  - threadpoolctl
  - folium
  - plotly
  - holoviews
  - hvplot
  - tqdm
  - ipython
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - pygeohash